modules-download-mode: readonly

linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - funlen
    - err113
    - gofumpt
    - gomoddirectives
    - makezero
    - varnamelen
    - exhaustruct
    - gomnd  # because WARN The linter 'gomnd' is deprecated (since v1.58.0) due to: The linter has been renamed. Replaced by mnd.
    - exportloopref  # because WARN The linter 'exportloopref' is deprecated (since v1.60.2) due to: Since Go1.22 (loopvar) this linter is no longer relevant. Replaced by copyloopvar.
    - execinquery  # because WARN The linter 'execinquery' is deprecated (since v1.58.0) due to: The repository of the linter has been archived by the owner.

linters-settings:
  cyclop:
    max-complexity: 15


issues:
  exclude:
    - import '.*' is not allowed from list 'Main'
  exclude-rules:
    - path: _test\.go
      linters:
        - testpackage
        - paralleltest
        - maligned
        - dupl
    - linters:
        - gosec
      text: "G401: "
    - linters:
        - gosec
      text: "G505: "
