modules-download-mode: readonly

linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - funlen
    - err113
    - gofumpt
    - gomoddirectives
    - makezero
    - varnamelen
    - exhaustruct

linters-settings:
  cyclop:
    max-complexity: 15


issues:
  exclude:
    - import '.*' is not allowed from list 'Main'
  exclude-rules:
    - path: _test\.go
      linters:
        - testpackage
        - paralleltest
        - maligned
        - dupl
    - linters:
        - gosec
      text: "G401: "
    - linters:
        - gosec
      text: "G505: "
